name: Node.js CI

on:  
  push:  
    branches: [ "master" ]  
  pull_request:  
    branches: [ "master" ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    strategy:  
      matrix:  
        node-version: [18.x]  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v3  

      - name: Use Node.js ${{ matrix.node-version }}  
        uses: actions/setup-node@v3  
        with:  
          node-version: ${{ matrix.node-version }}  
          cache: 'npm'  

      - name: Install Dependencies  
        run: npm ci  

      - name: Install Playwright Firefox  
        run: npx playwright install firefox  

      - name: Build Project  
        run: npm run build --if-present  

      - name: Run Tests  
        run: npm test file ./tests/LoginTestRunner.spec.js  
        continue-on-error: true  

      - name: Generate Allure Report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/
